import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tasko/features/todo/presentation/state/settings_provider.dart';

class AppLocalizations {
  final String languageCode;
  AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'Tasko',
      'organize': 'Organize your day',
      'hello': 'Hello',
      'home': 'Home',
      'tasks': 'Tasks',
      'calendar': 'Calendar',
      'profile': 'Profile',
      'settings': 'Settings',
      'today': 'TODAY',
      'tomorrow': 'TOMORROW',
      'add_task': 'Add New Task',
      'task_name': 'Task Name',
      'save': 'Save',
      'completed': 'completed',
      'no_tasks_today': 'No tasks for today',
      'no_tasks_tomorrow': 'No tasks for tomorrow',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'notifications': 'Notifications',
      'account_settings': 'Account Settings',
      'change_email': 'Change Email',
      'change_password': 'Change Password',
      'contact_us': 'Contact Us',
      'logout': 'Logout',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone': 'Phone Number',
      'country': 'Country',
      'bio': 'Bio',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'follow_us': 'Follow Us',
      'send_feedback': 'Send Feedback',
      'invite_friends': 'Invite Friends',
      'remove_tasks': 'Remove Tasks',
      'task_lists': 'Task Lists',
      'appearance': 'Appearance',
      'welcome_back': 'Welcome Back!',
      'sign_in_subtitle': 'Sign in to manage your tasks',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'forgot_password': 'Forgot Password?',
      'reset_password_title': 'Reset Password',
      'reset_password_disclaimer': 'Your password will be reset by verifying your registered email only. This does not confirm your identity in any other way.',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'password_mismatch': 'Passwords do not match',
      'account_not_found': 'No account found with this email.',
      'password_reset_success': 'Password reset successfully. You can now log in with your new password.',
      'notes': 'Notes',
      'time': 'Time',
      'priority': 'Priority',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'all': 'All',
      'done': 'Done',
      'pending': 'Pending',
      'search': 'Search tasks...',
       'no_tasks': 'No tasks yet! Tap + to add',
       'no_tasks_for_day': 'No tasks for this day',
       'no_upcoming': 'No upcoming tasks 🎉',
      'delete_all': 'Delete all tasks?',
      'delete_all_confirm_message': 'This will permanently delete all your tasks. This action cannot be undone.',
      'confirm': 'Confirm',
      'push_notifications': 'Push Notifications',
      'select_language': 'Select Language',
      'hello_user': 'Hello',
      'upcoming': 'Upcoming Tasks',
      'field_required': 'This field is required',
      'invalid_email': 'Please enter a valid email',
      'password_too_short': 'Password must be at least 6 characters',
      'invalid_credentials': 'Invalid email or password.',
      'continue_with_google': 'Continue with Google',
      'or': 'or',
      'google_sign_in_failed': 'Google sign-in failed. Please try again.',
      'email_hint': 'Enter your email',
      'password_hint': 'Enter your password',
      'sign_in': 'Sign In',
      'main_menu': 'MAIN MENU',
      'actions': 'ACTIONS',
      'teams': 'Teams',
      'my_teams': 'My Teams',
      'create_team': 'Create Team',
      'team_name': 'Team Name',
      'team_description': 'Description (optional)',
      'no_teams': 'No teams yet. Create your first team!',
      'edit': 'Edit',
      'delete_team': 'Delete Team',
      'delete_team_confirm': 'Are you sure you want to delete this team? Shared tasks will be removed.',
      'members': 'Members',
      'invitations': 'Invitations',
      'invite_member': 'Invite Member',
      'add_member': 'Add Member',
      'role': 'Role',
      'owner': 'Owner',
      'editor': 'Editor',
      'viewer': 'Viewer',
      'remove': 'Remove',
      'invite': 'Invite',
      'revoke': 'Revoke',
      'no_members': 'No members yet',
      'no_invitations': 'No pending invitations',
      'member_role_changed': 'Member role updated',
      'member_removed': 'Member removed',
      'invitation_sent': 'Invitation sent',
      'invitation_revoked': 'Invitation revoked',
      'accepted': 'Accepted',
      'declined': 'Declined',
      'revoked': 'Revoked',
      'you': 'You',
      'mark_all_read': 'Mark all as read',
      'no_notifications': 'No notifications yet',
      'unread': 'Unread',
      'search_placeholder': 'Search tasks, teams, tags...',
      'results': 'Results',
      'no_results': 'No results found',
      'type_to_search': 'Type to search',
      'analytics': 'Analytics',
      'completion_rate': 'Completion Rate',
      'overdue': 'Overdue',
      'total_tasks': 'Total Tasks',
      'completed_tasks': 'Completed',
      'by_priority': 'By Priority',
      'by_category': 'By Category',
      'completion_trend': 'Completion Trend',
      'activity': 'Activity',
      'no_activity': 'No activity yet',
      'admin_panel': 'Admin Panel',
      'users': 'Users',
      'user_management': 'User Management',
      'team_management': 'Team Management',
      'no_users': 'No users found',
      'search_users': 'Search users...',
      'set_admin': 'Set Admin',
      'set_user': 'Set User',
      'categories': 'Categories',
      'tags': 'Tags',
      'admin': 'Admin',
      'user_role': 'User',
      'search_menu': 'Search',
      'comments': 'Comments',
      'add_comment': 'Add comment',
      'comment_hint': 'Write a comment...',
      'no_comments': 'No comments yet. Be the first!',
      'delete_comment': 'Delete comment',
      'delete_comment_confirm': 'Delete this comment?',
      'comment_add_failed': 'Could not post your comment. Try again.',
      'send': 'Send',
      'continue_with_facebook': 'Continue with Facebook',
      'facebook_sign_in_failed': 'Facebook sign-in failed. Please try again.',
      'link_account_title': 'Confirm it\u2019s you',
      'link_account_password_message': 'An account already exists with this email. Confirm with your Tasko password to link it to Facebook.',
      'link_account_email_message': 'An account already exists with this email. To link it to Facebook, we\u2019ll email a one-time confirmation link to that address.',
      'link_account_confirm': 'Link Account',
      'send_confirmation_email': 'Send Confirmation Email',
      'check_inbox_title': 'Check your inbox',
      'check_inbox_message': 'We sent a confirmation link to your email. Open it, then tap \u201cContinue with Facebook\u201d again to finish signing in.',
      'ok': 'OK',
      'sign_in_method': 'Sign-in Method',
      'sign_in_method_password': 'Password',
      'sign_in_method_google': 'Google',
      'sign_in_method_facebook': 'Facebook',
      'sign_in_method_apple': 'Apple',
      'invite_title': 'Team Invitation',
      'invite_for_email': 'Invitation for {email}',
      'invite_role': 'Role',
      'invite_expires': 'Expires',
      'invite_accept': 'Accept Invitation',
      'invite_decline': 'Decline',
      'invite_accepted': 'You have joined the team!',
      'invite_declined': 'Invitation declined.',
      'invite_not_pending': 'This invitation is no longer pending.',
    },
    'ar': {
      'app_name': 'تاسكو',
      'organize': 'نظّم يومك',
      'hello': 'مرحباً',
      'home': 'الرئيسية',
      'tasks': 'المهام',
      'calendar': 'التقويم',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'add_task': 'إضافة مهمة',
      'task_name': 'اسم المهمة',
      'save': 'حفظ',
      'completed': 'مكتملة',
      'no_tasks_today': 'لا توجد مهام اليوم',
      'no_tasks_tomorrow': 'لا توجد مهام لغداً',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'account_settings': 'إعدادات الحساب',
      'change_email': 'تغيير البريد',
      'change_password': 'تغيير كلمة المرور',
      'contact_us': 'تواصل معنا',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'country': 'الدولة',
      'bio': 'نبذة شخصية',
      'edit_profile': 'تعديل الملف',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'follow_us': 'تابعنا',
      'send_feedback': 'إرسال تقييم',
      'invite_friends': 'دعوة أصدقاء',
      'remove_tasks': 'حذف المهام',
      'task_lists': 'قائمة المهام',
      'appearance': 'المظهر',
      'welcome_back': 'مرحباً بعودتك!',
      'sign_in_subtitle': 'سجّل دخولك لإدارة مهامك',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'forgot_password': 'نسيت كلمة المرور؟',
      'reset_password_title': 'إعادة تعيين كلمة المرور',
      'reset_password_disclaimer': 'سيتم إعادة تعيين كلمة المرور بالتحقق من بريدك الإلكتروني المسجل فقط. لا يؤكد هذا هويتك بأي طريقة أخرى.',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'account_not_found': 'لم يتم العثور على حساب بهذا البريد الإلكتروني.',
      'password_reset_success': 'تمت إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
      'notes': 'ملاحظات',
      'time': 'الوقت',
      'priority': 'الأولوية',
      'high': 'عالية',
      'medium': 'متوسطة',
      'low': 'منخفضة',
      'all': 'الكل',
      'done': 'مكتملة',
      'pending': 'قيد الانتظار',
      'search': 'البحث في المهام...',
       'no_tasks': 'لا توجد مهام! اضغط + للإضافة',
       'no_tasks_for_day': 'لا توجد مهام لهذا اليوم',
       'no_upcoming': 'لا توجد مهام قادمة 🎉',
      'delete_all': 'حذف جميع المهام؟',
      'delete_all_confirm_message': 'سيؤدي هذا إلى حذف جميع مهامك نهائياً. لا يمكن التراجع عن هذا الإجراء.',
      'confirm': 'تأكيد',
      'push_notifications': 'الإشعارات',
      'select_language': 'اختر اللغة',
      'hello_user': 'مرحباً',
      'upcoming': 'المهام القادمة',
      'field_required': 'هذا الحقل مطلوب',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'password_too_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'continue_with_google': 'المتابعة عبر Google',
      'or': 'أو',
      'google_sign_in_failed': 'تعذّر تسجيل الدخول عبر Google. حاول مرة أخرى.',
      'email_hint': 'أدخل بريدك الإلكتروني',
      'password_hint': 'أدخل كلمة المرور',
      'sign_in': 'تسجيل الدخول',
      'main_menu': 'القائمة الرئيسية',
      'actions': 'الإجراءات',
      'teams': 'الفرق',
      'my_teams': 'فرقي',
      'create_team': 'إنشاء فريق',
      'team_name': 'اسم الفريق',
      'team_description': 'الوصف (اختياري)',
      'no_teams': 'لا توجد فرق بعد. أنشئ فريقك الأول!',
      'edit': 'تعديل',
      'delete_team': 'حذف الفريق',
      'delete_team_confirm': 'هل أنت متأكد من حذف هذا الفريق؟ ستُحذف المهام المشتركة.',
      'members': 'الأعضاء',
      'invitations': 'الدعوات',
      'invite_member': 'دعوة عضو',
      'add_member': 'إضافة عضو',
      'role': 'الدور',
      'owner': 'المالك',
      'editor': 'محرر',
      'viewer': 'مشاهد',
      'remove': 'إزالة',
      'invite': 'دعوة',
      'revoke': 'إلغاء',
      'no_members': 'لا يوجد أعضاء بعد',
      'no_invitations': 'لا توجد دعوات معلقة',
      'member_role_changed': 'تم تحديث دور العضو',
      'member_removed': 'تمت إزالة العضو',
      'invitation_sent': 'تم إرسال الدعوة',
      'invitation_revoked': 'تم إلغاء الدعوة',
      'accepted': 'مقبولة',
      'declined': 'مرفوضة',
      'revoked': 'ملغاة',
      'you': 'أنت',
      'mark_all_read': 'تعليم الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات بعد',
      'unread': 'غير مقروء',
      'search_placeholder': 'ابحث في المهام والفرق والوسوم...',
      'results': 'النتائج',
      'no_results': 'لا توجد نتائج',
      'type_to_search': 'اكتب للبحث',
      'analytics': 'الإحصائيات',
      'completion_rate': 'معدل الإنجاز',
      'overdue': 'متأخرة',
      'total_tasks': 'إجمالي المهام',
      'completed_tasks': 'مكتملة',
      'by_priority': 'حسب الأولوية',
      'by_category': 'حسب الفئة',
      'completion_trend': 'اتجاه الإنجاز',
      'activity': 'النشاط',
      'no_activity': 'لا يوجد نشاط بعد',
      'admin_panel': 'لوحة التحكم',
      'users': 'المستخدمون',
      'user_management': 'إدارة المستخدمين',
      'team_management': 'إدارة الفرق',
      'no_users': 'لا يوجد مستخدمون',
      'search_users': 'البحث عن مستخدمين...',
      'set_admin': 'تعيين كمسؤول',
      'set_user': 'تعيين كمستخدم',
      'categories': 'الفئات',
      'tags': 'الوسوم',
      'admin': 'مسؤول',
      'user_role': 'مستخدم',
      'search_menu': 'البحث',
      'comments': 'التعليقات',
      'add_comment': 'أضف تعليقًا',
      'comment_hint': 'اكتب تعليقًا...',
      'no_comments': 'لا توجد تعليقات بعد. كن الأول!',
      'delete_comment': 'حذف التعليق',
      'delete_comment_confirm': 'حذف هذا التعليق؟',
      'comment_add_failed': 'تعذّر نشر تعليقك. حاول مرة أخرى.',
      'send': 'إرسال',
      'continue_with_facebook': 'المتابعة عبر Facebook',
      'facebook_sign_in_failed': 'تعذّر تسجيل الدخول عبر Facebook. حاول مرة أخرى.',
      'link_account_title': 'تأكيد هويتك',
      'link_account_password_message': 'يوجد حساب بهذا البريد الإلكتروني. أكّد باستخدام كلمة مرور Tasko لربطه بـ Facebook.',
      'link_account_email_message': 'يوجد حساب بهذا البريد الإلكتروني. لربطه بـ Facebook سنرسل رابط تأكيد لمرة واحدة إلى هذا البريد.',
      'link_account_confirm': 'ربط الحساب',
      'send_confirmation_email': 'إرسال بريد التأكيد',
      'check_inbox_title': 'تحقق من بريدك',
      'check_inbox_message': 'أرسلنا رابط تأكيد إلى بريدك الإلكتروني. افتحه ثم اضغط \u201cالمتابعة عبر Facebook\u201d مرة أخرى لإكمال تسجيل الدخول.',
      'ok': 'حسناً',
      'sign_in_method': 'طريقة تسجيل الدخول',
      'sign_in_method_password': 'كلمة المرور',
      'sign_in_method_google': 'Google',
      'sign_in_method_facebook': 'Facebook',
      'sign_in_method_apple': 'Apple',
      'invite_title': 'دعوة للانضمام للفريق',
      'invite_for_email': 'دعوة لـ {email}',
      'invite_role': 'الدور',
      'invite_expires': 'تنتهي في',
      'invite_accept': 'قبول الدعوة',
      'invite_decline': 'رفض',
      'invite_accepted': 'لقد انضممت إلى الفريق!',
      'invite_declined': 'تم رفض الدعوة.',
      'invite_not_pending': 'لم تعد هذه الدعوة معلقة.',
    },
    'fr': {
      'app_name': 'Tasko',
      'organize': 'Organisez votre journée',
      'hello': 'Bonjour',
      'home': 'Accueil',
      'tasks': 'Tâches',
      'calendar': 'Calendrier',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'today': "AUJOURD'HUI",
      'tomorrow': 'DEMAIN',
      'add_task': 'Ajouter une tâche',
      'task_name': 'Nom de la tâche',
      'save': 'Enregistrer',
      'completed': 'terminées',
      'no_tasks_today': 'Aucune tâche aujourd\'hui',
      'no_tasks_tomorrow': 'Aucune tâche pour demain',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'notifications': 'Notifications',
      'account_settings': 'Paramètres du compte',
      'change_email': 'Changer l\'email',
      'change_password': 'Changer le mot de passe',
      'contact_us': 'Nous contacter',
      'logout': 'Déconnexion',
      'login': 'Connexion',
      'sign_up': 'S\'inscrire',
      'email': 'Email',
      'password': 'Mot de passe',
      'full_name': 'Nom complet',
      'phone': 'Numéro de téléphone',
      'country': 'Pays',
      'bio': 'Biographie',
      'edit_profile': 'Modifier le profil',
      'save_changes': 'Sauvegarder',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'follow_us': 'Suivez-nous',
      'send_feedback': 'Envoyer un avis',
      'invite_friends': 'Inviter des amis',
      'remove_tasks': 'Supprimer les tâches',
      'task_lists': 'Liste des tâches',
      'appearance': 'Apparence',
      'welcome_back': 'Bon retour!',
      'sign_in_subtitle': 'Connectez-vous pour gérer vos tâches',
      'no_account': 'Pas de compte?',
      'have_account': 'Déjà un compte?',
      'forgot_password': 'Mot de passe oublié?',
      'reset_password_title': 'Réinitialiser le mot de passe',
      'reset_password_disclaimer': 'Votre mot de passe sera réinitialisé en vérifiant uniquement votre email enregistré. Cela ne confirme votre identité d\'aucune autre manière.',
      'new_password': 'Nouveau mot de passe',
      'confirm_new_password': 'Confirmer le nouveau mot de passe',
      'password_mismatch': 'Les mots de passe ne correspondent pas',
      'account_not_found': 'Aucun compte trouvé avec cet email.',
      'password_reset_success': 'Mot de passe réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
      'notes': 'Notes',
      'time': 'Heure',
      'priority': 'Priorité',
      'high': 'Haute',
      'medium': 'Moyenne',
      'low': 'Faible',
      'all': 'Tout',
      'done': 'Terminé',
      'pending': 'En attente',
      'search': 'Rechercher...',
       'no_tasks': 'Aucune tâche! Appuyez sur +',
       'no_tasks_for_day': 'Aucune tâche pour ce jour',
       'no_upcoming': 'Aucune tâche à venir 🎉',
      'delete_all': 'Supprimer toutes les tâches?',
      'delete_all_confirm_message': 'Cela supprimera définitivement toutes vos tâches. Cette action est irréversible.',
      'confirm': 'Confirmer',
      'push_notifications': 'Notifications push',
      'select_language': 'Choisir la langue',
      'hello_user': 'Bonjour',
      'upcoming': 'Tâches à venir',
      'field_required': 'Ce champ est requis',
      'invalid_email': 'Veuillez entrer un email valide',
      'password_too_short': 'Le mot de passe doit comporter au moins 6 caractères',
      'invalid_credentials': 'Email ou mot de passe incorrect.',
      'continue_with_google': 'Continuer avec Google',
      'or': 'ou',
      'google_sign_in_failed': 'La connexion avec Google a échoué. Veuillez réessayer.',
      'email_hint': 'Entrez votre email',
      'password_hint': 'Entrez votre mot de passe',
      'sign_in': 'Se connecter',
      'main_menu': 'MENU PRINCIPAL',
      'actions': 'ACTIONS',
      'teams': 'Équipes',
      'my_teams': 'Mes équipes',
      'create_team': 'Créer une équipe',
      'team_name': 'Nom de l\'équipe',
      'team_description': 'Description (facultatif)',
      'no_teams': 'Aucune équipe pour l\'instant. Créez votre première équipe !',
      'edit': 'Modifier',
      'delete_team': 'Supprimer l\'équipe',
      'delete_team_confirm': 'Voulez-vous vraiment supprimer cette équipe ? Les tâches partagées seront supprimées.',
      'members': 'Membres',
      'invitations': 'Invitations',
      'invite_member': 'Inviter un membre',
      'add_member': 'Ajouter un membre',
      'role': 'Rôle',
      'owner': 'Propriétaire',
      'editor': 'Éditeur',
      'viewer': 'Lecteur',
      'remove': 'Retirer',
      'invite': 'Inviter',
      'revoke': 'Révoquer',
      'no_members': 'Aucun membre pour l\'instant',
      'no_invitations': 'Aucune invitation en attente',
      'member_role_changed': 'Rôle du membre mis à jour',
      'member_removed': 'Membre retiré',
      'invitation_sent': 'Invitation envoyée',
      'invitation_revoked': 'Invitation révoquée',
      'accepted': 'Acceptée',
      'declined': 'Refusée',
      'revoked': 'Révoquée',
      'you': 'Vous',
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications': 'Aucune notification pour l\'instant',
      'unread': 'Non lu',
      'search_placeholder': 'Rechercher tâches, équipes, tags...',
      'results': 'Résultats',
      'no_results': 'Aucun résultat',
      'type_to_search': 'Tapez pour rechercher',
      'analytics': 'Statistiques',
      'completion_rate': 'Taux de complétion',
      'overdue': 'En retard',
      'total_tasks': 'Total des tâches',
      'completed_tasks': 'Terminées',
      'by_priority': 'Par priorité',
      'by_category': 'Par catégorie',
      'completion_trend': 'Tendance de complétion',
      'activity': 'Activité',
      'no_activity': 'Aucune activité pour l\'instant',
      'admin_panel': 'Panneau d\'administration',
      'users': 'Utilisateurs',
      'user_management': 'Gestion des utilisateurs',
      'team_management': 'Gestion des équipes',
      'no_users': 'Aucun utilisateur',
      'search_users': 'Rechercher des utilisateurs...',
      'set_admin': 'Définir administrateur',
      'set_user': 'Définir utilisateur',
      'categories': 'Catégories',
      'tags': 'Tags',
      'admin': 'Admin',
      'user_role': 'Utilisateur',
      'search_menu': 'Rechercher',
      'comments': 'Commentaires',
      'add_comment': 'Ajouter un commentaire',
      'comment_hint': 'Écrire un commentaire...',
      'no_comments': 'Aucun commentaire pour le moment. Soyez le premier !',
      'delete_comment': 'Supprimer le commentaire',
      'delete_comment_confirm': 'Supprimer ce commentaire ?',
      'comment_add_failed': 'Impossible de publier votre commentaire. Réessayez.',
      'send': 'Envoyer',
      'continue_with_facebook': 'Continuer avec Facebook',
      'facebook_sign_in_failed': 'La connexion avec Facebook a échoué. Veuillez réessayer.',
      'link_account_title': 'Confirmez votre identité',
      'link_account_password_message': 'Un compte existe déjà avec cet email. Confirmez avec votre mot de passe Tasko pour le lier à Facebook.',
      'link_account_email_message': 'Un compte existe déjà avec cet email. Pour le lier à Facebook, nous enverrons un lien de confirmation à usage unique à cette adresse.',
      'link_account_confirm': 'Lier le compte',
      'send_confirmation_email': 'Envoyer le mail de confirmation',
      'check_inbox_title': 'Vérifiez votre boîte mail',
      'check_inbox_message': 'Nous avons envoyé un lien de confirmation à votre email. Ouvrez-le, puis touchez \u00ab Continuer avec Facebook \u00bb pour terminer la connexion.',
      'ok': 'OK',
      'sign_in_method': 'Méthode de connexion',
      'sign_in_method_password': 'Mot de passe',
      'sign_in_method_google': 'Google',
      'sign_in_method_facebook': 'Facebook',
      'sign_in_method_apple': 'Apple',
      'invite_title': 'Invitation d\'équipe',
      'invite_for_email': 'Invitation pour {email}',
      'invite_role': 'Rôle',
      'invite_expires': 'Expire le',
      'invite_accept': 'Accepter l\'invitation',
      'invite_decline': 'Refuser',
      'invite_accepted': 'Vous avez rejoint l\'équipe !',
      'invite_declined': 'Invitation refusée.',
      'invite_not_pending': 'Cette invitation n\'est plus en attente.',
    },
  };

  String get(String key) {
    return _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    final lang = context.watch<SettingsProvider>().language;
    return AppLocalizations(lang);
  }

  /// Read-only variant safe to call from event handlers (outside `build`).
  static AppLocalizations read(BuildContext context) {
    final lang = context.read<SettingsProvider>().language;
    return AppLocalizations(lang);
  }
}
