import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:tasko/features/todo/presentation/state/settings_provider.dart';

class AppLocalizations {
  final String languageCode;
  AppLocalizations(this.languageCode);

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'Tasko',
      'organize': 'Organize your day',
      'hello': 'Hello',
      'home': 'Home',
      'tasks': 'Tasks',
      'calendar': 'Calendar',
      'profile': 'Profile',
      'settings': 'Settings',
      'today': 'TODAY',
      'tomorrow': 'TOMORROW',
      'add_task': 'Add New Task',
      'task_name': 'Task Name',
      'save': 'Save',
      'completed': 'completed',
      'no_tasks_today': 'No tasks for today',
      'no_tasks_tomorrow': 'No tasks for tomorrow',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'notifications': 'Notifications',
      'account_settings': 'Account Settings',
      'change_email': 'Change Email',
      'change_password': 'Change Password',
      'contact_us': 'Contact Us',
      'logout': 'Logout',
      'login': 'Login',
      'sign_up': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'full_name': 'Full Name',
      'phone': 'Phone Number',
      'country': 'Country',
      'bio': 'Bio',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'follow_us': 'Follow Us',
      'send_feedback': 'Send Feedback',
      'invite_friends': 'Invite Friends',
      'remove_tasks': 'Remove Tasks',
      'task_lists': 'Task Lists',
      'appearance': 'Appearance',
      'welcome_back': 'Welcome Back!',
      'sign_in_subtitle': 'Sign in to manage your tasks',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'forgot_password': 'Forgot Password?',
      'notes': 'Notes',
      'time': 'Time',
      'priority': 'Priority',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'all': 'All',
      'done': 'Done',
      'pending': 'Pending',
      'search': 'Search tasks...',
       'no_tasks': 'No tasks yet! Tap + to add',
       'no_tasks_for_day': 'No tasks for this day',
       'no_upcoming': 'No upcoming tasks 🎉',
      'delete_all': 'Delete all tasks?',
      'confirm': 'Confirm',
      'push_notifications': 'Push Notifications',
      'select_language': 'Select Language',
      'hello_user': 'Hello',
      'upcoming': 'Upcoming Tasks',
      'field_required': 'This field is required',
      'invalid_email': 'Please enter a valid email',
      'password_too_short': 'Password must be at least 6 characters',
      'invalid_credentials': 'Invalid email or password.',
      'email_hint': 'Enter your email',
      'password_hint': 'Enter your password',
      'sign_in': 'Sign In',
      'main_menu': 'MAIN MENU',
      'actions': 'ACTIONS',
    },
    'ar': {
      'app_name': 'تاسكو',
      'organize': 'نظّم يومك',
      'hello': 'مرحباً',
      'home': 'الرئيسية',
      'tasks': 'المهام',
      'calendar': 'التقويم',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'today': 'اليوم',
      'tomorrow': 'غداً',
      'add_task': 'إضافة مهمة',
      'task_name': 'اسم المهمة',
      'save': 'حفظ',
      'completed': 'مكتملة',
      'no_tasks_today': 'لا توجد مهام اليوم',
      'no_tasks_tomorrow': 'لا توجد مهام لغداً',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'notifications': 'الإشعارات',
      'account_settings': 'إعدادات الحساب',
      'change_email': 'تغيير البريد',
      'change_password': 'تغيير كلمة المرور',
      'contact_us': 'تواصل معنا',
      'logout': 'تسجيل الخروج',
      'login': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'full_name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'country': 'الدولة',
      'bio': 'نبذة شخصية',
      'edit_profile': 'تعديل الملف',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'follow_us': 'تابعنا',
      'send_feedback': 'إرسال تقييم',
      'invite_friends': 'دعوة أصدقاء',
      'remove_tasks': 'حذف المهام',
      'task_lists': 'قائمة المهام',
      'appearance': 'المظهر',
      'welcome_back': 'مرحباً بعودتك!',
      'sign_in_subtitle': 'سجّل دخولك لإدارة مهامك',
      'no_account': 'ليس لديك حساب؟',
      'have_account': 'لديك حساب بالفعل؟',
      'forgot_password': 'نسيت كلمة المرور؟',
      'notes': 'ملاحظات',
      'time': 'الوقت',
      'priority': 'الأولوية',
      'high': 'عالية',
      'medium': 'متوسطة',
      'low': 'منخفضة',
      'all': 'الكل',
      'done': 'مكتملة',
      'pending': 'قيد الانتظار',
      'search': 'البحث في المهام...',
       'no_tasks': 'لا توجد مهام! اضغط + للإضافة',
       'no_tasks_for_day': 'لا توجد مهام لهذا اليوم',
       'no_upcoming': 'لا توجد مهام قادمة 🎉',
      'delete_all': 'حذف جميع المهام؟',
      'confirm': 'تأكيد',
      'push_notifications': 'الإشعارات',
      'select_language': 'اختر اللغة',
      'hello_user': 'مرحباً',
      'upcoming': 'المهام القادمة',
      'field_required': 'هذا الحقل مطلوب',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'password_too_short': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      'email_hint': 'أدخل بريدك الإلكتروني',
      'password_hint': 'أدخل كلمة المرور',
      'sign_in': 'تسجيل الدخول',
      'main_menu': 'القائمة الرئيسية',
      'actions': 'الإجراءات',
    },
    'fr': {
      'app_name': 'Tasko',
      'organize': 'Organisez votre journée',
      'hello': 'Bonjour',
      'home': 'Accueil',
      'tasks': 'Tâches',
      'calendar': 'Calendrier',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'today': "AUJOURD'HUI",
      'tomorrow': 'DEMAIN',
      'add_task': 'Ajouter une tâche',
      'task_name': 'Nom de la tâche',
      'save': 'Enregistrer',
      'completed': 'terminées',
      'no_tasks_today': 'Aucune tâche aujourd\'hui',
      'no_tasks_tomorrow': 'Aucune tâche pour demain',
      'dark_mode': 'Mode sombre',
      'language': 'Langue',
      'notifications': 'Notifications',
      'account_settings': 'Paramètres du compte',
      'change_email': 'Changer l\'email',
      'change_password': 'Changer le mot de passe',
      'contact_us': 'Nous contacter',
      'logout': 'Déconnexion',
      'login': 'Connexion',
      'sign_up': 'S\'inscrire',
      'email': 'Email',
      'password': 'Mot de passe',
      'full_name': 'Nom complet',
      'phone': 'Numéro de téléphone',
      'country': 'Pays',
      'bio': 'Biographie',
      'edit_profile': 'Modifier le profil',
      'save_changes': 'Sauvegarder',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'follow_us': 'Suivez-nous',
      'send_feedback': 'Envoyer un avis',
      'invite_friends': 'Inviter des amis',
      'remove_tasks': 'Supprimer les tâches',
      'task_lists': 'Liste des tâches',
      'appearance': 'Apparence',
      'welcome_back': 'Bon retour!',
      'sign_in_subtitle': 'Connectez-vous pour gérer vos tâches',
      'no_account': 'Pas de compte?',
      'have_account': 'Déjà un compte?',
      'forgot_password': 'Mot de passe oublié?',
      'notes': 'Notes',
      'time': 'Heure',
      'priority': 'Priorité',
      'high': 'Haute',
      'medium': 'Moyenne',
      'low': 'Faible',
      'all': 'Tout',
      'done': 'Terminé',
      'pending': 'En attente',
      'search': 'Rechercher...',
       'no_tasks': 'Aucune tâche! Appuyez sur +',
       'no_tasks_for_day': 'Aucune tâche pour ce jour',
       'no_upcoming': 'Aucune tâche à venir 🎉',
      'delete_all': 'Supprimer toutes les tâches?',
      'confirm': 'Confirmer',
      'push_notifications': 'Notifications push',
      'select_language': 'Choisir la langue',
      'hello_user': 'Bonjour',
      'upcoming': 'Tâches à venir',
      'field_required': 'Ce champ est requis',
      'invalid_email': 'Veuillez entrer un email valide',
      'password_too_short': 'Le mot de passe doit comporter au moins 6 caractères',
      'invalid_credentials': 'Email ou mot de passe incorrect.',
      'email_hint': 'Entrez votre email',
      'password_hint': 'Entrez votre mot de passe',
      'sign_in': 'Se connecter',
      'main_menu': 'MENU PRINCIPAL',
      'actions': 'ACTIONS',
    },
  };

  String get(String key) {
    return _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    final lang = context.watch<SettingsProvider>().language;
    return AppLocalizations(lang);
  }
}
