import { TaskPriority } from '../../../common/constants/task-priority.enum';
import {
  TaskSortBy,
  TaskSortDir,
} from '../../../common/constants/task-sort-by.enum';
import { TagEntity } from '../../tag/entities/tag.entity';
import { TaskEntity } from '../entities/task.entity';

/**
 * Concrete filters for a task list query. The service resolves relative day
 * filters (`today`/`tomorrow`) into `relativeLabel` + `relativeIso`; the
 * repository only translates them into SQL.
 *
 * A list is scoped either to a user (personal tasks, `teamId` IS NULL) or to a
 * team (all tasks whose `teamId` matches). Exactly one of the two is set.
 */
export interface TaskListOptions {
  userId?: string;
  teamId?: string;
  /** When set, matches tasks whose label equals this OR whose date is `relativeIso`. */
  relativeLabel?: 'today' | 'tomorrow';
  relativeIso?: string;
  /** Inclusive yyyy-MM-dd range. Only matches ISO-labelled tasks. */
  dateFrom?: string;
  dateTo?: string;
  priority?: TaskPriority;
  isDone?: boolean;
  categoryId?: string;
  tagId?: string;
  query?: string;
  sortBy: TaskSortBy;
  sortDir: TaskSortDir;
  page: number;
  limit: number;
}

/**
 * Search across the caller's personal tasks plus every team they belong to.
 * `teamIds` is empty when the caller has no teams (personal scope only).
 */
export interface TaskSearchOptions {
  q: string;
  userId: string;
  teamIds: string[];
  page: number;
  limit: number;
}

/**
 * A lightweight task projection used by analytics. `categoryName` is resolved
 * by a join so breakdowns can be labelled without extra round-trips.
 */
export interface AnalyticsRow {
  id: string;
  isDone: boolean;
  priority: TaskPriority;
  date: string;
  categoryId: string | null;
  categoryName: string | null;
  completedAt: Date | null;
}

/** Analytics scope: exactly one of `userId` (personal) or `teamId` is set. */
export interface AnalyticsScope {
  userId?: string;
  teamId?: string;
}

export interface CreateTaskData {
  /** Client-generated id; omitted ids are generated by the DB layer. */
  id?: string;
  userId: string;
  /** NULL for personal tasks. */
  teamId: string | null;
  title: string;
  time: string;
  date: string;
  isDone: boolean;
  priority: TaskPriority;
  notes: string | null;
  categoryId: string | null;
  tags: TagEntity[];
  completedAt: Date | null;
}

/** Data access contract for tasks. */
export abstract class TaskRepository {
  abstract findById(id: string): Promise<TaskEntity | null>;

  /** Loads a task including its tags relation. */
  abstract findByIdWithTags(id: string): Promise<TaskEntity | null>;

  /** Returns a page of tasks matching `options` and the total matching count. */
  abstract listAndCount(
    options: TaskListOptions,
  ): Promise<[TaskEntity[], number]>;

  /** Searches title/notes across personal + team tasks. */
  abstract search(options: TaskSearchOptions): Promise<[TaskEntity[], number]>;

  /** Loads a lightweight projection of every task in scope for analytics. */
  abstract listForAnalytics(scope: AnalyticsScope): Promise<AnalyticsRow[]>;

  abstract create(data: CreateTaskData): Promise<TaskEntity>;

  abstract save(entity: TaskEntity): Promise<TaskEntity>;

  abstract remove(id: string): Promise<void>;

  /** Admin stats: total task rows. */
  abstract countAll(): Promise<number>;

  /** Admin stats: total completed task rows. */
  abstract countCompleted(): Promise<number>;
}
