import { TaskPriority } from '../../../common/constants/task-priority.enum';
import {
  TaskSortBy,
  TaskSortDir,
} from '../../../common/constants/task-sort-by.enum';
import { TagEntity } from '../../tag/entities/tag.entity';
import { TaskEntity } from '../entities/task.entity';

/**
 * Concrete filters for a task list query. The service resolves relative day
 * filters (`today`/`tomorrow`) into `relativeLabel` + `relativeIso`; the
 * repository only translates them into SQL.
 *
 * A list is scoped either to a user (personal tasks, `teamId` IS NULL) or to a
 * team (all tasks whose `teamId` matches). Exactly one of the two is set.
 */
export interface TaskListOptions {
  userId?: string;
  teamId?: string;
  /** When set, matches tasks whose label equals this OR whose date is `relativeIso`. */
  relativeLabel?: 'today' | 'tomorrow';
  relativeIso?: string;
  /** Inclusive yyyy-MM-dd range. Only matches ISO-labelled tasks. */
  dateFrom?: string;
  dateTo?: string;
  priority?: TaskPriority;
  isDone?: boolean;
  categoryId?: string;
  tagId?: string;
  query?: string;
  sortBy: TaskSortBy;
  sortDir: TaskSortDir;
  page: number;
  limit: number;
}

export interface CreateTaskData {
  /** Client-generated id; omitted ids are generated by the DB layer. */
  id?: string;
  userId: string;
  /** NULL for personal tasks. */
  teamId: string | null;
  title: string;
  time: string;
  date: string;
  isDone: boolean;
  priority: TaskPriority;
  notes: string | null;
  categoryId: string | null;
  tags: TagEntity[];
}

/** Data access contract for tasks. */
export abstract class TaskRepository {
  abstract findById(id: string): Promise<TaskEntity | null>;

  /** Loads a task including its tags relation. */
  abstract findByIdWithTags(id: string): Promise<TaskEntity | null>;

  /** Returns a page of tasks matching `options` and the total matching count. */
  abstract listAndCount(
    options: TaskListOptions,
  ): Promise<[TaskEntity[], number]>;

  abstract create(data: CreateTaskData): Promise<TaskEntity>;

  abstract save(entity: TaskEntity): Promise<TaskEntity>;

  abstract remove(id: string): Promise<void>;
}
